sudo: required
services:
  - docker

before_install:
  - docker build -t maainul/docker-react -f Dockerfile.dev .

install: travis_wait mvn install
script:
  - travis_wait docker run maainul/docker-react npm run test -- --coverage
